### ISSUE TITLE
WHAT HAPPENED TO THE SITE!?

### ISSUE THREAD

**Issue by angelotrabuco2013** [Dinosaurmod/dinosaurmod.github.io#2]
**UPDATE:** It appears to be a Node.js workflow issue. The site may go back up shortly.

**UPDATE:** Replacement is out, 2.0 is coming out somewhere in the next 3 months

**UPDATE:** Site is operating again!

What a shame...

**Look at the commits:**
![image](https://github.com/Dinosaurmod/dinosaurmod.github.io/assets/153839847/a4f72c4d-6e28-43cc-a631-0b69a4ccb7b9)

Did it just shut down completely?

I can't believe what just happened to the site, it stopped functioning.

@GabsTheCuriousKid, are you going to make another mod? The site seems to have abandoned itself. If not, then i'll try something else.

**Comment by GabsTheCuriousKid** [comment]
it all probably started on the "change some things" commit, i think it was the colors.css that caused the error. but i don't know why. i changed colors.css but it didn't work. i am asking Mr_rudy on scratch. if he isn't able to tell me how to fix it and/or im not able to fix this issue, i might aswell remake dinosaurmod.

**Comment by angelotrabuco2013** [comment]
Oh, OK.

**Comment by angelotrabuco2013** [comment]
> i might aswell remake dinosaurmod.

Gabs, what mod do you prefer to fork? TurboWarp or PenguinMod?

**Comment by angelotrabuco2013** [comment]
Bump (surpassed a new hour, 18:00 BRT)

**Comment by angelotrabuco2013** [comment]
Bump (surpassed a half minute, 18:05 BRT)

**Comment by GabsTheCuriousKid** [comment]
> > i might aswell remake dinosaurmod.
> 
> Gabs, what mod do you prefer to fork? TurboWarp or PenguinMod?
>
i prefer to fork penguinmod (for now) because, i tried to fork turbowarp once and failed.

**Comment by angelotrabuco2013** [comment]
Umm, OK.

**Comment by GabsTheCuriousKid** [comment]
> > > > i might aswell remake dinosaurmod.
> > >
> > >
> > > Gabs, what mod do you prefer to fork? TurboWarp or PenguinMod?
> >
> > i prefer to fork penguinmod (for now) because, i tried to fork turbowarp once and failed.
>
because dinosaurmod is down, im making a replacement, it's basically for when dinosaurmod is down, it's still being worked on.

**Comment by GabsTheCuriousKid** [comment]
https://dinosaurmod.github.io/replacement

**Comment by angelotrabuco2013** [comment]
> https://dinosaurmod.github.io/replacement

Thank you so much! I can't wait for the second revision.

**Comment by angelotrabuco2013** [comment]
Gabs, the link on your profile seem to be outdated, please update the link.

It should be: https://dinosaurmod.github.io/replacement

**Comment by angelotrabuco2013** [comment]
**Update**: has gone down again.

**Comment by angelotrabuco2013** [comment]
It might be a problem with SharkPool's extension gallery listed-on-site.

**Comment by angelotrabuco2013** [comment]
The followup on this situation is seen here as a log.
![Captura de Tela (2)](https://github.com/Dinosaurmod/dinosaurmod.github.io/assets/153839847/eda6672e-fa3d-43ce-87db-3dfba96aa2d1)

**Comment by angelotrabuco2013** [comment]
bump

**Comment by angelotrabuco2013** [comment]
bump again (github is flagging my comment as similar)

**Comment by angelotrabuco2013** [comment]
The PenguinMod website is still accessible, with the following links:
Preview: https://penguinmod-home-lao0e5j76-penguinmod.vercel.app
Production: https://penguinmod.com

**Comment by angelotrabuco2013** [comment]
bump (nearly 18:40 BRT)

**Comment by GabsTheCuriousKid** [comment]
> The followup on this situation is seen here as a log. ![Captura de Tela (2)](https://private-user-images.githubusercontent.com/153839847/293790724-eda6672e-fa3d-43ce-87db-3dfba96aa2d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzQ5MTEsIm5iZiI6MTcwNDIzNDYxMSwicGF0aCI6Ii8xNTM4Mzk4NDcvMjkzNzkwNzI0LWVkYTY2NzJlLWZhM2QtNDNjZS04N2RiLTNkZmJhOTZhYTJkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQyMjMwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzU4MzM1NjhiOTQ3YWVmZWNhOWVhYmQ5M2ZiN2ZkMmEyMTc1MWNkMWY2OTRiMjc3MTMzMTQ4Nzk4YjY5ZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avOzYYSdQBGRFhW8VWWvEm-449TGc9Ej7jpQpzIhKlM)

thanks for reminding me, dinosaurmod is back!

**Comment by angelotrabuco2013** [comment]
The site is working properly again, thanks!

**Comment by GabsTheCuriousKid** [comment]
> The site is working properly again, thanks!

your welcome
